server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '******'
  jpa:
    database: mysql
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379
    password: '******'
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
#  data:
#      mongodb:
#        host: localhost
#        port: 27017
#        username: user
#        password: 123456
#        database: test
#        authenticationDatabase: test
mongo:
  host: localhost
  port: 27017
  name: test
